// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IHFiction.Data.Migrations
{
    /// <inheritdoc />
    public partial class ModelSync : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_work_stories_story_id",
                schema: "ihfiction.dev2",
                table: "work");

            migrationBuilder.AddColumn<int>(
                name: "order",
                schema: "ihfiction.dev2",
                table: "work",
                type: "integer",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "order",
                schema: "ihfiction.dev2",
                table: "work");

            migrationBuilder.AddForeignKey(
                name: "fk_work_stories_story_id",
                schema: "ihfiction.dev2",
                table: "work",
                column: "story_id",
                principalSchema: "ihfiction.dev2",
                principalTable: "work",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);
        }
    }
}
