// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IHFiction.Data.Migrations
{
    /// <inheritdoc />
    public partial class SomeUpdate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_tag_tag_canonical_tag_id",
                schema: "ihfiction.dev2",
                table: "tag");

            migrationBuilder.DropForeignKey(
                name: "fk_tag_work_tag_tags_id",
                schema: "ihfiction.dev2",
                table: "tag_work");

            migrationBuilder.DropPrimaryKey(
                name: "pk_tag",
                schema: "ihfiction.dev2",
                table: "tag");

            migrationBuilder.RenameTable(
                name: "tag",
                schema: "ihfiction.dev2",
                newName: "tags",
                newSchema: "ihfiction.dev2");

            migrationBuilder.RenameIndex(
                name: "ix_tag_canonical_tag_id",
                schema: "ihfiction.dev2",
                table: "tags",
                newName: "ix_tags_canonical_tag_id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_tags",
                schema: "ihfiction.dev2",
                table: "tags",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "fk_tag_work_tags_tags_id",
                schema: "ihfiction.dev2",
                table: "tag_work",
                column: "tags_id",
                principalSchema: "ihfiction.dev2",
                principalTable: "tags",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_tags_tags_canonical_tag_id",
                schema: "ihfiction.dev2",
                table: "tags",
                column: "canonical_tag_id",
                principalSchema: "ihfiction.dev2",
                principalTable: "tags",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_work_work_story_id",
                schema: "ihfiction.dev2",
                table: "work",
                column: "story_id",
                principalSchema: "ihfiction.dev2",
                principalTable: "work",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_tag_work_tags_tags_id",
                schema: "ihfiction.dev2",
                table: "tag_work");

            migrationBuilder.DropForeignKey(
                name: "fk_tags_tags_canonical_tag_id",
                schema: "ihfiction.dev2",
                table: "tags");

            migrationBuilder.DropForeignKey(
                name: "fk_work_work_story_id",
                schema: "ihfiction.dev2",
                table: "work");

            migrationBuilder.DropPrimaryKey(
                name: "pk_tags",
                schema: "ihfiction.dev2",
                table: "tags");

            migrationBuilder.RenameTable(
                name: "tags",
                schema: "ihfiction.dev2",
                newName: "tag",
                newSchema: "ihfiction.dev2");

            migrationBuilder.RenameIndex(
                name: "ix_tags_canonical_tag_id",
                schema: "ihfiction.dev2",
                table: "tag",
                newName: "ix_tag_canonical_tag_id");

            migrationBuilder.AddPrimaryKey(
                name: "pk_tag",
                schema: "ihfiction.dev2",
                table: "tag",
                column: "id");

            migrationBuilder.AddForeignKey(
                name: "fk_tag_tag_canonical_tag_id",
                schema: "ihfiction.dev2",
                table: "tag",
                column: "canonical_tag_id",
                principalSchema: "ihfiction.dev2",
                principalTable: "tag",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "fk_tag_work_tag_tags_id",
                schema: "ihfiction.dev2",
                table: "tag_work",
                column: "tags_id",
                principalSchema: "ihfiction.dev2",
                principalTable: "tag",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
