// <auto-generated />
using System;
using IHFiction.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IHFiction.Data.Migrations
{
    [DbContext(typeof(FictionDbContext))]
    [Migration("20260805064824_AddStoryCompletionStatus")]
    partial class AddStoryCompletionStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ihfiction.dev2")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("WolverineEnabled", "true");

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnthologyStory", b =>
                {
                    b.Property<string>("AnthologiesId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("anthologies_id");

                    b.Property<string>("StoriesId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("stories_id");

                    b.HasKey("AnthologiesId", "StoriesId")
                        .HasName("pk_anthology_story");

                    b.HasIndex("StoriesId")
                        .HasDatabaseName("ix_anthology_story_stories_id");

                    b.ToTable("anthology_story", "ihfiction.dev2");
                });

            modelBuilder.Entity("AuthorWork", b =>
                {
                    b.Property<string>("AuthorsId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("authors_id");

                    b.Property<string>("WorksId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("works_id");

                    b.HasKey("AuthorsId", "WorksId")
                        .HasName("pk_author_work");

                    b.HasIndex("WorksId")
                        .HasDatabaseName("ix_author_work_works_id");

                    b.ToTable("author_work", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.Authors.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("discriminator");

                    b.Property<string>("GravatarEmail")
                        .HasColumnType("text")
                        .HasColumnName("gravatar_email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", "ihfiction.dev2");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("IHFiction.Data.BrowserReports.Domain.BrowserReportPayloadRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("BlockedResource")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("blocked_resource");

                    b.Property<int?>("ColumnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("column_number");

                    b.Property<string>("Disposition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("disposition");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("LastUserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_user_agent");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_count");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("payload_hash");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("ReportResource")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("report_url");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("report_type");

                    b.Property<string>("SourceFile")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_file");

                    b.Property<string>("SummaryKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary_key");

                    b.Property<string>("SummaryMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("summary_message");

                    b.HasKey("Id")
                        .HasName("pk_browser_report_payloads");

                    b.HasIndex("ReportType", "PayloadHash")
                        .IsUnique()
                        .HasDatabaseName("ix_browser_report_payloads_report_type_payload_hash");

                    b.ToTable("browser_report_payloads", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.BrowserReports.Domain.CspViolationReportRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("BlockedResource")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("blocked_url");

                    b.Property<string>("Disposition")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("disposition");

                    b.Property<string>("DocumentResource")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("document_url");

                    b.Property<string>("EffectiveDirective")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("effective_directive");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<int?>("LastColumnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_column_number");

                    b.Property<int?>("LastLineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_line_number");

                    b.Property<string>("LastSample")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_sample");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("LastUserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_user_agent");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_count");

                    b.Property<string>("OriginalPolicy")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("original_policy");

                    b.Property<string>("SourceFile")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_file");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id")
                        .HasName("pk_csp_violation_reports");

                    b.HasIndex("Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_csp_violation_reports_fingerprint");

                    b.ToTable("csp_violation_reports", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.DeviceAuthorFollow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("author_id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_author_follows");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_device_author_follows_author_id");

                    b.HasIndex("DeviceId", "AuthorId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_author_follows_device_id_author_id");

                    b.ToTable("device_author_follows", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.DeviceNotificationDelivery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("notification_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_notification_deliveries");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_device_notification_deliveries_notification_id");

                    b.HasIndex("DeviceId", "NotificationId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_notification_deliveries_device_id_notification_id");

                    b.ToTable("device_notification_deliveries", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.DevicePushSubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("auth_key");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failure_at");

                    b.Property<DateTime?>("LastSuccessfulDeliveryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_delivery_at");

                    b.Property<string>("P256dhKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("p256dh_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_device_push_subscriptions");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_device_push_subscriptions_device_id");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_device_push_subscriptions_endpoint");

                    b.ToTable("device_push_subscriptions", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.DeviceStoryFollow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("StoryId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("story_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_device_story_follows");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_device_story_follows_story_id");

                    b.HasIndex("DeviceId", "StoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_device_story_follows_device_id_story_id");

                    b.ToTable("device_story_follows", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.NotificationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("body");

                    b.Property<string>("ChapterId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("chapter_id");

                    b.Property<DateTime>("EventOccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_occurred_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<string>("NotificationKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("notification_key");

                    b.Property<string>("StoryId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("story_id");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("target_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_notifications_author_id");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_notifications_chapter_id");

                    b.HasIndex("NotificationKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_notification_key");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_notifications_story_id");

                    b.ToTable("notifications", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.UserAuthorFollow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("author_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_author_follows");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_user_author_follows_author_id");

                    b.HasIndex("UserId", "AuthorId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_author_follows_user_id_author_id");

                    b.ToTable("user_author_follows", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.UserNotificationDelivery", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("notification_id");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_notification_deliveries");

                    b.HasIndex("NotificationId")
                        .HasDatabaseName("ix_user_notification_deliveries_notification_id");

                    b.HasIndex("UserId", "NotificationId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_notification_deliveries_user_id_notification_id");

                    b.ToTable("user_notification_deliveries", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.UserPushSubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("AuthKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("auth_key");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_failure_at");

                    b.Property<DateTime?>("LastSuccessfulDeliveryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_delivery_at");

                    b.Property<string>("P256dhKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("p256dh_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_push_subscriptions");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_user_push_subscriptions_endpoint");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_push_subscriptions_user_id");

                    b.ToTable("user_push_subscriptions", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.UserStoryFollow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("StoryId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("story_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_story_follows");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_user_story_follows_story_id");

                    b.HasIndex("UserId", "StoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_story_follows_user_id_story_id");

                    b.ToTable("user_story_follows", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.Searching.Domain.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("discriminator");

                    b.Property<string>("Subcategory")
                        .HasColumnType("text")
                        .HasColumnName("subcategory");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.ToTable("tags", "ihfiction.dev2");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Tag");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.StoryCover", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("StoryId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("story_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_story_covers");

                    b.HasIndex("StoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_story_covers_story_id");

                    b.ToTable("story_covers", "ihfiction.dev2");
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.Work", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("discriminator");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("owner_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("ReadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("read_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_works");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_works_owner_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_works_title");

                    b.ToTable("works", "ihfiction.dev2");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Work");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.WorkRead", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("id");

                    b.Property<DateTime>("FirstReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_read_at");

                    b.Property<bool>("IsCounted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_counted");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_read_at");

                    b.Property<string>("ReaderKey")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("reader_key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("work_id");

                    b.HasKey("Id")
                        .HasName("pk_work_reads");

                    b.HasIndex("ReaderKey", "LastReadAt")
                        .HasDatabaseName("ix_work_reads_reader_key_last_read_at");

                    b.HasIndex("WorkId", "ReaderKey")
                        .IsUnique()
                        .HasDatabaseName("ix_work_reads_work_id_reader_key");

                    b.ToTable("work_reads", "ihfiction.dev2");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys", "ihfiction.dev2");
                });

            modelBuilder.Entity("TagWork", b =>
                {
                    b.Property<string>("TagsId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("tags_id");

                    b.Property<string>("WorksId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("works_id");

                    b.HasKey("TagsId", "WorksId")
                        .HasName("pk_tag_work");

                    b.HasIndex("WorksId")
                        .HasDatabaseName("ix_tag_work_works_id");

                    b.ToTable("tag_work", "ihfiction.dev2");
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.IncomingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_time");

                    b.Property<DateTimeOffset?>("KeepUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("keep_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("text")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_incoming_envelopes");

                    b.ToTable("wolverine_incoming_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Wolverine.EntityFrameworkCore.Internals.OutgoingMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset?>("DeliverBy")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deliver_by");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_wolverine_outgoing_envelopes");

                    b.ToTable("wolverine_outgoing_envelopes", "wolverine", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("IHFiction.Data.Authors.Domain.Author", b =>
                {
                    b.HasBaseType("IHFiction.Data.Authors.Domain.User");

                    b.HasDiscriminator().HasValue("Author");
                });

            modelBuilder.Entity("IHFiction.Data.Searching.Domain.CanonicalTag", b =>
                {
                    b.HasBaseType("IHFiction.Data.Searching.Domain.Tag");

                    b.ToTable("tags", "ihfiction.dev2");

                    b.HasDiscriminator().HasValue("CanonicalTag");
                });

            modelBuilder.Entity("IHFiction.Data.Searching.Domain.SynonymTag", b =>
                {
                    b.HasBaseType("IHFiction.Data.Searching.Domain.Tag");

                    b.Property<string>("CanonicalTagId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("canonical_tag_id");

                    b.HasIndex("CanonicalTagId")
                        .HasDatabaseName("ix_tags_canonical_tag_id");

                    b.ToTable("tags", "ihfiction.dev2");

                    b.HasDiscriminator().HasValue("SynonymTag");
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.Anthology", b =>
                {
                    b.HasBaseType("IHFiction.Data.Stories.Domain.Work");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasDiscriminator().HasValue("Anthology");
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.Book", b =>
                {
                    b.HasBaseType("IHFiction.Data.Stories.Domain.Work");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("StoryId")
                        .IsRequired()
                        .HasColumnType("character varying(26)")
                        .HasColumnName("story_id");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_works_story_id");

                    b.HasDiscriminator().HasValue("Book");
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.Chapter", b =>
                {
                    b.HasBaseType("IHFiction.Data.Stories.Domain.Work");

                    b.Property<string>("BookId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("book_id");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("StoryId")
                        .HasColumnType("character varying(26)")
                        .HasColumnName("story_id");

                    b.Property<string>("WorkBodyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_body_id");

                    b.HasIndex("BookId")
                        .HasDatabaseName("ix_works_book_id");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_works_story_id");

                    b.HasDiscriminator().HasValue("Chapter");
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.Story", b =>
                {
                    b.HasBaseType("IHFiction.Data.Stories.Domain.Work");

                    b.Property<string>("CompletionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("completion_status");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("WorkBodyId")
                        .HasColumnType("text")
                        .HasColumnName("work_body_id");

                    b.HasDiscriminator().HasValue("Story");
                });

            modelBuilder.Entity("AnthologyStory", b =>
                {
                    b.HasOne("IHFiction.Data.Stories.Domain.Anthology", null)
                        .WithMany()
                        .HasForeignKey("AnthologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anthology_story_anthologies_anthologies_id");

                    b.HasOne("IHFiction.Data.Stories.Domain.Story", null)
                        .WithMany()
                        .HasForeignKey("StoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anthology_story_stories_stories_id");
                });

            modelBuilder.Entity("AuthorWork", b =>
                {
                    b.HasOne("IHFiction.Data.Authors.Domain.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_author_work_authors_authors_id");

                    b.HasOne("IHFiction.Data.Stories.Domain.Work", null)
                        .WithMany()
                        .HasForeignKey("WorksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_author_work_works_works_id");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.DeviceAuthorFollow", b =>
                {
                    b.HasOne("IHFiction.Data.Authors.Domain.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_author_follows_authors_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.DeviceNotificationDelivery", b =>
                {
                    b.HasOne("IHFiction.Data.Notifications.Domain.NotificationRecord", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_notification_deliveries_notifications_notification_id");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.DeviceStoryFollow", b =>
                {
                    b.HasOne("IHFiction.Data.Stories.Domain.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_story_follows_stories_story_id");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.NotificationRecord", b =>
                {
                    b.HasOne("IHFiction.Data.Authors.Domain.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_authors_author_id");

                    b.HasOne("IHFiction.Data.Stories.Domain.Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_chapters_chapter_id");

                    b.HasOne("IHFiction.Data.Stories.Domain.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_stories_story_id");

                    b.Navigation("Author");

                    b.Navigation("Chapter");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.UserAuthorFollow", b =>
                {
                    b.HasOne("IHFiction.Data.Authors.Domain.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_author_follows_authors_author_id");

                    b.HasOne("IHFiction.Data.Authors.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_author_follows_users_user_id");

                    b.Navigation("Author");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.UserNotificationDelivery", b =>
                {
                    b.HasOne("IHFiction.Data.Notifications.Domain.NotificationRecord", "Notification")
                        .WithMany()
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notification_deliveries_notifications_notification_id");

                    b.HasOne("IHFiction.Data.Authors.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notification_deliveries_users_user_id");

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.UserPushSubscription", b =>
                {
                    b.HasOne("IHFiction.Data.Authors.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_push_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IHFiction.Data.Notifications.Domain.UserStoryFollow", b =>
                {
                    b.HasOne("IHFiction.Data.Stories.Domain.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_story_follows_stories_story_id");

                    b.HasOne("IHFiction.Data.Authors.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_story_follows_users_user_id");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.StoryCover", b =>
                {
                    b.HasOne("IHFiction.Data.Stories.Domain.Story", "Story")
                        .WithOne("Cover")
                        .HasForeignKey("IHFiction.Data.Stories.Domain.StoryCover", "StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_covers_stories_story_id");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.Work", b =>
                {
                    b.HasOne("IHFiction.Data.Authors.Domain.Author", "Owner")
                        .WithMany("OwnedWorks")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_works_authors_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.WorkRead", b =>
                {
                    b.HasOne("IHFiction.Data.Stories.Domain.Work", "Work")
                        .WithMany()
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_work_reads_works_work_id");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("TagWork", b =>
                {
                    b.HasOne("IHFiction.Data.Searching.Domain.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_work_tags_tags_id");

                    b.HasOne("IHFiction.Data.Stories.Domain.Work", null)
                        .WithMany()
                        .HasForeignKey("WorksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_work_works_works_id");
                });

            modelBuilder.Entity("IHFiction.Data.Authors.Domain.Author", b =>
                {
                    b.OwnsOne("IHFiction.Data.Authors.Domain.Profile", "Profile", b1 =>
                        {
                            b1.Property<string>("AuthorId")
                                .HasColumnType("character varying(26)")
                                .HasColumnName("id");

                            b1.Property<string>("Bio")
                                .HasColumnType("text")
                                .HasColumnName("profile_bio");

                            b1.HasKey("AuthorId");

                            b1.ToTable("users", "ihfiction.dev2");

                            b1.WithOwner()
                                .HasForeignKey("AuthorId")
                                .HasConstraintName("fk_authors_authors_id");

                            b1.OwnsMany("IHFiction.Data.Authors.Domain.SocialLink", "SocialLinks", b2 =>
                                {
                                    b2.Property<string>("author_id")
                                        .HasColumnType("character varying(26)")
                                        .HasColumnName("author_id");

                                    b2.Property<string>("Type")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("type");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("value");

                                    b2.HasKey("author_id", "Type")
                                        .HasName("pk_author_social_links");

                                    b2.HasIndex("author_id", "Type")
                                        .IsUnique()
                                        .HasDatabaseName("ix_author_social_links_author_id_type");

                                    b2.ToTable("author_social_links", "ihfiction.dev2");

                                    b2.WithOwner()
                                        .HasForeignKey("author_id")
                                        .HasConstraintName("fk_author_social_links_authors_author_id");
                                });

                            b1.Navigation("SocialLinks");
                        });

                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("IHFiction.Data.Searching.Domain.SynonymTag", b =>
                {
                    b.HasOne("IHFiction.Data.Searching.Domain.CanonicalTag", "CanonicalTag")
                        .WithMany("Synonyms")
                        .HasForeignKey("CanonicalTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_tags_canonical_tag_id");

                    b.Navigation("CanonicalTag");
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.Book", b =>
                {
                    b.HasOne("IHFiction.Data.Stories.Domain.Story", "Story")
                        .WithMany("Books")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_works_works_story_id");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.Chapter", b =>
                {
                    b.HasOne("IHFiction.Data.Stories.Domain.Book", "Book")
                        .WithMany("Chapters")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_works_works_book_id");

                    b.HasOne("IHFiction.Data.Stories.Domain.Story", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_works_works_story_id");

                    b.Navigation("Book");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("IHFiction.Data.Authors.Domain.Author", b =>
                {
                    b.Navigation("OwnedWorks");
                });

            modelBuilder.Entity("IHFiction.Data.Searching.Domain.CanonicalTag", b =>
                {
                    b.Navigation("Synonyms");
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.Book", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("IHFiction.Data.Stories.Domain.Story", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Chapters");

                    b.Navigation("Cover");
                });
#pragma warning restore 612, 618
        }
    }
}
