name: Delete old workflow runs
on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: Mattraks/delete-workflow-runs@b3018382ca039b53d238908238bd35d1fb14f8ee # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 30
          keep_minimum_runs: 5